"""add features_metadata column to fixtures

Revision ID: 8e22981990f9
Revises: d05f4bf8ffa8
Create Date: 2026-01-15 14:26:29.406053+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e22981990f9'
down_revision: str | None = 'd05f4bf8ffa8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('features_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'features_metadata')
    # ### end Alembic commands ###
