"""add team_computed_stats and backtest_jobs tables

Revision ID: 2aaaf9e8fd7f
Revises: 43fec3039ba3
Create Date: 2026-01-14 13:48:50.166565+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2aaaf9e8fd7f'
down_revision: str | None = '43fec3039ba3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('bet_type', sa.String(length=20), nullable=False),
    sa.Column('seasons', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_jobs_filter_id'), 'backtest_jobs', ['filter_id'], unique=False)
    op.create_index(op.f('ix_backtest_jobs_id'), 'backtest_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_jobs_job_id'), 'backtest_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_backtest_jobs_status'), 'backtest_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_jobs_user_id'), 'backtest_jobs', ['user_id'], unique=False)
    op.create_table('team_computed_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('goals_scored_avg', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('goals_conceded_avg', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('clean_sheet_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('failed_to_score', sa.Integer(), nullable=False),
    sa.Column('failed_to_score_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('points_per_game', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('home_matches', sa.Integer(), nullable=False),
    sa.Column('home_wins', sa.Integer(), nullable=False),
    sa.Column('home_draws', sa.Integer(), nullable=False),
    sa.Column('home_losses', sa.Integer(), nullable=False),
    sa.Column('home_goals_scored_avg', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('home_goals_conceded_avg', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('away_matches', sa.Integer(), nullable=False),
    sa.Column('away_wins', sa.Integer(), nullable=False),
    sa.Column('away_draws', sa.Integer(), nullable=False),
    sa.Column('away_losses', sa.Integer(), nullable=False),
    sa.Column('away_goals_scored_avg', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('away_goals_conceded_avg', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('form_last5_wins', sa.Integer(), nullable=False),
    sa.Column('form_last5_draws', sa.Integer(), nullable=False),
    sa.Column('form_last5_losses', sa.Integer(), nullable=False),
    sa.Column('form_last5_points', sa.Integer(), nullable=False),
    sa.Column('form_last5_goals_scored', sa.Integer(), nullable=False),
    sa.Column('form_last5_goals_conceded', sa.Integer(), nullable=False),
    sa.Column('form_last10_wins', sa.Integer(), nullable=False),
    sa.Column('form_last10_draws', sa.Integer(), nullable=False),
    sa.Column('form_last10_losses', sa.Integer(), nullable=False),
    sa.Column('form_last10_points', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season_type', name='uq_team_season_stats')
    )
    op.create_index(op.f('ix_team_computed_stats_id'), 'team_computed_stats', ['id'], unique=False)
    op.create_index(op.f('ix_team_computed_stats_season_type'), 'team_computed_stats', ['season_type'], unique=False)
    op.create_index(op.f('ix_team_computed_stats_team_id'), 'team_computed_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_computed_stats_team_id'), table_name='team_computed_stats')
    op.drop_index(op.f('ix_team_computed_stats_season_type'), table_name='team_computed_stats')
    op.drop_index(op.f('ix_team_computed_stats_id'), table_name='team_computed_stats')
    op.drop_table('team_computed_stats')
    op.drop_index(op.f('ix_backtest_jobs_user_id'), table_name='backtest_jobs')
    op.drop_index(op.f('ix_backtest_jobs_status'), table_name='backtest_jobs')
    op.drop_index(op.f('ix_backtest_jobs_job_id'), table_name='backtest_jobs')
    op.drop_index(op.f('ix_backtest_jobs_id'), table_name='backtest_jobs')
    op.drop_index(op.f('ix_backtest_jobs_filter_id'), table_name='backtest_jobs')
    op.drop_table('backtest_jobs')
    # ### end Alembic commands ###
