"""add unique constraint to team_stats

Revision ID: a0cae0d934ff
Revises: fix_team_cols
Create Date: 2026-01-15 13:01:21.524597+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a0cae0d934ff'
down_revision: str | None = 'fix_team_cols'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixtures_metadata'), table_name='fixtures', postgresql_using='gin')
    op.drop_column('fixtures', 'metadata')
    op.execute('DROP INDEX ix_leagues_league_id CASCADE')
    op.create_index(op.f('ix_leagues_league_id'), 'leagues', ['league_id'], unique=False)
    op.create_unique_constraint('uq_league_season', 'leagues', ['league_id', 'season_type', 'year'])
    op.create_unique_constraint('uq_team_stats_event_team', 'team_stats', ['event_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_stats_event_team', 'team_stats', type_='unique')
    op.drop_constraint('uq_league_season', 'leagues', type_='unique')
    op.execute('DROP INDEX ix_leagues_league_id CASCADE')
    op.create_index(op.f('ix_leagues_league_id'), 'leagues', ['league_id'], unique=True)
    op.add_column('fixtures', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_fixtures_metadata'), 'fixtures', ['metadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
