"""Add core models for Phase 2

Revision ID: 43fec3039ba3
Revises: 
Create Date: 2026-01-14 10:17:31.330075+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43fec3039ba3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=255), nullable=False),
    sa.Column('season_slug', sa.String(length=100), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('midsize_name', sa.String(length=100), nullable=True),
    sa.Column('league_name', sa.String(length=255), nullable=False),
    sa.Column('league_short_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_index(op.f('ix_leagues_league_id'), 'leagues', ['league_id'], unique=True)
    op.create_index(op.f('ix_leagues_season_type'), 'leagues', ['season_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_venue_id'), 'venues', ['venue_id'], unique=True)
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filters_id'), 'filters', ['id'], unique=False)
    op.create_index(op.f('ix_filters_user_id'), 'filters', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('short_display_name', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('alternate_color', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=True)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('bet_type', sa.String(length=20), nullable=False),
    sa.Column('seasons', sa.String(length=100), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('pushes', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('roi_percentage', sa.Float(), nullable=False),
    sa.Column('avg_odds', sa.Float(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_filter_id'), 'backtest_results', ['filter_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_team_winner', sa.Boolean(), nullable=True),
    sa.Column('away_team_winner', sa.Boolean(), nullable=True),
    sa.Column('home_team_score', sa.Integer(), nullable=True),
    sa.Column('away_team_score', sa.Integer(), nullable=True),
    sa.Column('home_team_shootout_score', sa.Integer(), nullable=True),
    sa.Column('away_team_shootout_score', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_away_team_id'), 'fixtures', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_event_id'), 'fixtures', ['event_id'], unique=True)
    op.create_index(op.f('ix_fixtures_home_team_id'), 'fixtures', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_id'), 'fixtures', ['id'], unique=False)
    op.create_index(op.f('ix_fixtures_league_id'), 'fixtures', ['league_id'], unique=False)
    op.create_index(op.f('ix_fixtures_match_date'), 'fixtures', ['match_date'], unique=False)
    op.create_index(op.f('ix_fixtures_season_type'), 'fixtures', ['season_type'], unique=False)
    op.create_index(op.f('ix_fixtures_status_id'), 'fixtures', ['status_id'], unique=False)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('last_match_datetime', sa.DateTime(), nullable=True),
    sa.Column('team_rank', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Float(), nullable=True),
    sa.Column('goals_against', sa.Float(), nullable=True),
    sa.Column('goal_difference', sa.Float(), nullable=True),
    sa.Column('deductions', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Float(), nullable=True),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('next_opponent', sa.String(length=100), nullable=True),
    sa.Column('next_home_away', sa.String(length=10), nullable=True),
    sa.Column('next_match_datetime', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standings_id'), 'standings', ['id'], unique=False)
    op.create_index(op.f('ix_standings_league_id'), 'standings', ['league_id'], unique=False)
    op.create_index(op.f('ix_standings_season_type'), 'standings', ['season_type'], unique=False)
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_order', sa.Integer(), nullable=True),
    sa.Column('possession_pct', sa.Float(), nullable=True),
    sa.Column('fouls_committed', sa.Float(), nullable=True),
    sa.Column('yellow_cards', sa.Float(), nullable=True),
    sa.Column('red_cards', sa.Float(), nullable=True),
    sa.Column('offsides', sa.Float(), nullable=True),
    sa.Column('won_corners', sa.Float(), nullable=True),
    sa.Column('saves', sa.Float(), nullable=True),
    sa.Column('total_shots', sa.Float(), nullable=True),
    sa.Column('shots_on_target', sa.Float(), nullable=True),
    sa.Column('shot_pct', sa.Float(), nullable=True),
    sa.Column('penalty_kick_goals', sa.Float(), nullable=True),
    sa.Column('penalty_kick_shots', sa.Float(), nullable=True),
    sa.Column('accurate_passes', sa.Float(), nullable=True),
    sa.Column('total_passes', sa.Float(), nullable=True),
    sa.Column('pass_pct', sa.Float(), nullable=True),
    sa.Column('accurate_crosses', sa.Float(), nullable=True),
    sa.Column('total_crosses', sa.Float(), nullable=True),
    sa.Column('cross_pct', sa.Float(), nullable=True),
    sa.Column('total_long_balls', sa.Float(), nullable=True),
    sa.Column('accurate_long_balls', sa.Float(), nullable=True),
    sa.Column('longball_pct', sa.Float(), nullable=True),
    sa.Column('blocked_shots', sa.Float(), nullable=True),
    sa.Column('effective_tackles', sa.Float(), nullable=True),
    sa.Column('total_tackles', sa.Float(), nullable=True),
    sa.Column('tackle_pct', sa.Float(), nullable=True),
    sa.Column('interceptions', sa.Float(), nullable=True),
    sa.Column('effective_clearance', sa.Float(), nullable=True),
    sa.Column('total_clearance', sa.Float(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['fixtures.event_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_stats_event_id'), 'team_stats', ['event_id'], unique=False)
    op.create_index(op.f('ix_team_stats_id'), 'team_stats', ['id'], unique=False)
    op.create_index(op.f('ix_team_stats_season_type'), 'team_stats', ['season_type'], unique=False)
    op.create_index(op.f('ix_team_stats_team_id'), 'team_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_stats_team_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_season_type'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_event_id'), table_name='team_stats')
    op.drop_table('team_stats')
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_season_type'), table_name='standings')
    op.drop_index(op.f('ix_standings_league_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_id'), table_name='standings')
    op.drop_table('standings')
    op.drop_index(op.f('ix_fixtures_status_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_season_type'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_match_date'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_league_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_home_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_event_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_away_team_id'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_filter_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_filters_user_id'), table_name='filters')
    op.drop_index(op.f('ix_filters_id'), table_name='filters')
    op.drop_table('filters')
    op.drop_index(op.f('ix_venues_venue_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_leagues_season_type'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_league_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
