"""add logo_url to leagues

Revision ID: 886f4f006caa
Revises: 8e22981990f9
Create Date: 2026-01-16 13:30:52.717471+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '886f4f006caa'
down_revision: str | None = '8e22981990f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'logo_url')
    # ### end Alembic commands ###
