"""add unique constraint to standings

Revision ID: d05f4bf8ffa8
Revises: a0cae0d934ff
Create Date: 2026-01-15 13:24:47.827897+00:00

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd05f4bf8ffa8'
down_revision: str | None = 'a0cae0d934ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create the unique constraint for standings for now
    # Foreign key constraints will be added in a separate migration
    op.create_unique_constraint('uq_standing_season_league_team', 'standings', ['season_type', 'league_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_standing_season_league_team', 'standings', type_='unique')
    # ### end Alembic commands ###
